# IMPORT LIBRARIES

In [28]:
import pandas as pd
from skrub import TableReport
from skore import EstimatorReport, CrossValidationReport

# Extra Resources

In [ ]:
# https://soda-inria.github.io/ken_embeddings/
# https://skrub-data.org/stable/auto_examples/06_ken_embeddings.html
#!pip install "skrub[transformers]"
#!pip install skrub -U

In [85]:
df = pd.read_csv("dataset/imdb.csv")

In [86]:
cols_to_drop = [
    "countryOfOrigin",
    "genres",
    "soundMixes",
    "continent",
    "filtered_genres",
    "filtered_soundMixes",
    "Unnamed: 0",
]
df = df.drop(columns=cols_to_drop)

KeyError: "['continent', 'filtered_genres', 'filtered_soundMixes', 'Unnamed: 0'] not found in axis"

In [87]:
TableReport(df)

Processing column  32 / 32

In [88]:
from skrub import tabular_learner

In [90]:
target = "rating"

In [91]:
X = df.drop(columns=[f"{target}", "averageRating"])
y = df[target]

In [94]:
model = tabular_learner("classification").fit(X, y)
report = CrossValidationReport(estimator=model, X=X, y=y)
report.metrics.report_metrics(indicator_favorability=True)

Output()

Output()

                                 HistGradientBoostingClassifier            \
                                                           mean       std
Metric           Label / Average
Precision        (0, 1]                                0.000000  0.000000
                 (1, 2]                                0.011525  0.008730
                 (2, 3]                                0.062726  0.015574
                 (3, 4]                                0.267367  0.091798
                 (4, 5]                                0.374327  0.043944
                 (5, 6]                                0.352960  0.058162
                 (6, 7]                                0.267340  0.047380
                 (7, 8]                                0.369564  0.010631
                 (8, 9]                                0.231349  0.130650
                 (9, 10]                               0.322130  0.258225
Recall           (0, 1]                                0.000000  0.000000
                 (1, 2]                                0.018992  0.013734
                 (2, 3]                                0.025395  0.010405
                 (3, 4]                                0.044725  0.020313
                 (4, 5]                                0.079793  0.037924
                 (5, 6]                                0.241923  0.303543
                 (6, 7]                                0.251467  0.066934
                 (7, 8]                                0.585027  0.268367
                 (8, 9]                                0.074596  0.044712
                 (9, 10]                               0.055128  0.043948
ROC AUC          (0, 1]                                0.531765  0.149192
                 (1, 2]                                0.623480  0.041613
                 (2, 3]                                0.720086  0.022395
                 (3, 4]                                0.789084  0.049779
                 (4, 5]                                0.782795  0.056623
                 (5, 6]                                0.699614  0.069229
                 (6, 7]                                0.520378  0.049739
                 (7, 8]                                0.631757  0.031494
                 (8, 9]                                0.649329  0.116897
                 (9, 10]                               0.772411  0.070017
Log loss                                               1.768426  0.126955
Fit time (s)                                          19.628109  1.361505
Predict time (s)                                       3.575411  0.889767

                                 Favorability

Metric           Label / Average
Precision        (0, 1]                  (↗︎)
                 (1, 2]                  (↗︎)
                 (2, 3]                  (↗︎)
                 (3, 4]                  (↗︎)
                 (4, 5]                  (↗︎)
                 (5, 6]                  (↗︎)
                 (6, 7]                  (↗︎)
                 (7, 8]                  (↗︎)
                 (8, 9]                  (↗︎)
                 (9, 10]                 (↗︎)
Recall           (0, 1]                  (↗︎)
                 (1, 2]                  (↗︎)
                 (2, 3]                  (↗︎)
                 (3, 4]                  (↗︎)
                 (4, 5]                  (↗︎)
                 (5, 6]                  (↗︎)
                 (6, 7]                  (↗︎)
                 (7, 8]                  (↗︎)
                 (8, 9]                  (↗︎)
                 (9, 10]                 (↗︎)
ROC AUC          (0, 1]                  (↗︎)
                 (1, 2]                  (↗︎)
                 (2, 3]                  (↗︎)
                 (3, 4]                  (↗︎)
                 (4, 5]                  (↗︎)
                 (5, 6]                  (↗︎)
                 (6, 7]                  (↗︎)
                 (7, 8]                  (↗︎)
                 (8, 9]                  (↗︎)
                 (9, 10]                 (↗︎)
Log loss                                 (↘︎)
Fit time (s)                             (↘︎)
Predict time (s)                         (↘︎)

In [95]:
report.metrics.accuracy()

Output()

         HistGradientBoostingClassifier
                                   mean       std
Metric
Accuracy                       0.308833  0.032757

In [97]:
tabular_learner("classification")

Pipeline(steps=[('tablevectorizer',
                 TableVectorizer(high_cardinality=MinHashEncoder(),
                                 low_cardinality=ToCategorical())),
                ('histgradientboostingclassifier',
                 HistGradientBoostingClassifier(categorical_features='from_dtype'))])

In [96]:
model.named_steps["tablevectorizer"].transform(X)

,originalTitle_00,originalTitle_01,originalTitle_02,originalTitle_03,originalTitle_04,originalTitle_05,originalTitle_06,originalTitle_07,originalTitle_08,originalTitle_09,...,soundMixes_21,soundMixes_22,soundMixes_23,soundMixes_24,soundMixes_25,soundMixes_26,soundMixes_27,soundMixes_28,soundMixes_29,quotesTotal
0,-1.961993e+09,-1.944660e+09,-1.730382e+09,-2.074643e+09,-2.103581e+09,-1.928435e+09,-2.084143e+09,-8.935505e+08,-1.887077e+09,-2.092068e+09,...,-2.031918e+09,-1.529326e+09,-2.070032e+09,-1.987735e+09,-1.799709e+09,-1.744838e+09,-1.707980e+09,-2.120210e+09,-1.548162e+09,0.0
1,-2.073325e+09,-2.040825e+09,-1.617070e+09,-1.904512e+09,-2.139598e+09,-2.098378e+09,-2.002096e+09,-1.422654e+09,-1.465632e+09,-2.007882e+09,...,-2.031918e+09,-1.529326e+09,-2.070032e+09,-1.987735e+09,-1.799709e+09,-1.744838e+09,-1.707980e+09,-2.120210e+09,-1.548162e+09,0.0
2,-2.056310e+09,-2.022347e+09,-1.986773e+09,-1.656275e+09,-1.743543e+09,-2.006491e+09,-2.136127e+09,-2.063006e+09,-2.131704e+09,-1.613215e+09,...,-2.031918e+09,-1.529326e+09,-2.070032e+09,-1.987735e+09,-1.799709e+09,-1.744838e+09,-1.707980e+09,-2.120210e+09,-1.548162e+09,0.0
3,-2.073325e+09,-2.143365e+09,-2.052492e+09,-2.090637e+09,-2.099561e+09,-2.125982e+09,-2.136127e+09,-2.066141e+09,-2.143665e+09,-1.820160e+09,...,-2.031918e+09,-1.529326e+09,-2.070032e+09,-1.987735e+09,-1.799709e+09,-1.744838e+09,-1.707980e+09,-2.120210e+09,-1.548162e+09,0.0
4,-2.137647e+09,-2.137928e+09,-2.103289e+09,-1.896353e+09,-2.117221e+09,-2.127402e+09,-2.084343e+09,-2.063006e+09,-2.119827e+09,-2.137107e+09,...,-2.031918e+09,-1.529326e+09,-2.070032e+09,-1.987735e+09,-1.799709e+09,-1.744838e+09,-1.707980e+09,-2.120210e+09,-1.548162e+09,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149526,-1.850010e+09,-2.116390e+09,-2.146331e+09,-2.133959e+09,-1.988711e+09,-1.948226e+09,-1.786493e+09,-2.028686e+09,-2.073760e+09,-1.421713e+09,...,-1.628056e+09,-1.395995e+09,-1.917268e+08,-1.099863e+09,-3.632171e+08,8.440901e+08,-2.107865e+09,-1.115898e+09,2.207017e+08,0.0
149527,-1.890865e+09,-2.068788e+08,-1.255821e+09,2.928563e+07,-1.267292e+09,-9.433431e+08,-1.876905e+09,-9.799374e+08,-1.274688e+09,-8.699089e+08,...,-1.628056e+09,-1.395995e+09,-1.917268e+08,-1.099863e+09,-3.632171e+08,8.440901e+08,-2.107865e+09,-1.115898e+09,2.207017e+08,0.0
149528,-2.085421e+09,-2.022347e+09,-2.089176e+09,-1.993853e+09,-2.112906e+09,-2.035219e+09,-2.084704e+09,-2.053089e+09,-2.074403e+09,-2.123293e+09,...,-1.628056e+09,-1.395995e+09,-1.917268e+08,-1.099863e+09,-3.632171e+08,8.440901e+08,-2.107865e+09,-1.115898e+09,2.207017e+08,0.0
149529,-2.135328e+09,-2.022347e+09,-2.052492e+09,-2.107102e+09,-2.099561e+09,-2.127402e+09,-2.114004e+09,-2.063006e+09,-2.106787e+09,-2.087500e+09,...,-1.628056e+09,-1.395995e+09,-1.917268e+08,-1.099863e+09,-3.632171e+08,8.440901e+08,-2.107865e+09,-1.115898e+09,2.207017e+08,0.0
149530,-2.110212e+09,-2.077288e+09,-2.072722e+09,-2.126967e+09,-2.099561e+09,-2.116572e+09,-1.973684e+09,-2.094201e+09,-1.977473e+09,-2.019223e+09,...,-1.628056e+09,-1.395995e+09,-1.917268e+08,-1.099863e+09,-3.632171e+08,8.440901e+08,-2.107865e+09,-1.115898e+09,2.207017e+08,0.0

In [ ]:
model.named_steps["tablevectorizer"].

AttributeError: 'TableVectorizer' object has no attribute 'help'

In [56]:
df2 = pd.read_csv("dataset/train_post_outlier.csv")

In [57]:
cols_to_drop = [
    "countryOfOrigin",
    "genres",
    "soundMixes",
    "continent",
    "filtered_genres",
    "filtered_soundMixes",
    "Unnamed: 0",
]
df2 = df2.drop(columns=cols_to_drop)

In [58]:
cols_to_drop = ["has_awards", "awardWins", "canHaveEpisodes"]
df2 = df2.drop(columns=cols_to_drop)

In [59]:
TableReport(df2)

Processing column  57 / 57

In [60]:
X = df2.drop(columns=["averageRating", "rating_category"])
y = df2["rating_category"]

In [61]:
model = tabular_learner("classifier").fit(X, y)
report = EstimatorReport(estimator=model, X_test=X, y_test=y, fit="False")
report.metrics.report_metrics(indicator_favorability=True)

                                  HistGradientBoostingClassifier Favorability
Metric           Label / Average
Precision        High                                   0.425029         (↗︎)
                 Low                                    0.482708         (↗︎)
                 Medium                                 0.501855         (↗︎)
                 Very High                              0.434441         (↗︎)
                 Very Low                               0.538477         (↗︎)
Recall           High                                   0.588385         (↗︎)
                 Low                                    0.362586         (↗︎)
                 Medium                                 0.228136         (↗︎)
                 Very High                              0.499272         (↗︎)
                 Very Low                               0.661350         (↗︎)
ROC AUC          High                                   0.769769         (↗︎)
                 Low                                    0.753267         (↗︎)
                 Medium                                 0.721305         (↗︎)
                 Very High                              0.820022         (↗︎)
                 Very Low                               0.856047         (↗︎)
Log loss                                                1.267813         (↘︎)
Fit time (s)                                                 NaN         (↘︎)
Predict time (s)                                        0.563473         (↘︎)

In [77]:
report = CrossValidationReport(estimator=model, X=X, y=y, cv_splitter=4)

Output()

In [78]:
report.metrics.report_metrics(indicator_favorability=True)

Output()

                                 HistGradientBoostingClassifier            \
                                                           mean       std
Metric           Label / Average
Precision        High                                  0.357640  0.017900
                 Low                                   0.389323  0.006259
                 Medium                                0.331058  0.009507
                 Very High                             0.368455  0.012676
                 Very Low                              0.503835  0.023903
Recall           High                                  0.531723  0.042779
                 Low                                   0.290010  0.011934
                 Medium                                0.141348  0.007349
                 Very High                             0.392938  0.042068
                 Very Low                              0.610591  0.024127
ROC AUC          High                                  0.711141  0.020253
                 Low                                   0.691194  0.008396
                 Medium                                0.636665  0.019328
                 Very High                             0.748977  0.046335
                 Very Low                              0.824193  0.015297
Log loss                                               1.399343  0.092778
Fit time (s)                                           5.595512  0.426326
Predict time (s)                                       0.171880  0.021740

                                 Favorability

Metric           Label / Average
Precision        High                    (↗︎)
                 Low                     (↗︎)
                 Medium                  (↗︎)
                 Very High               (↗︎)
                 Very Low                (↗︎)
Recall           High                    (↗︎)
                 Low                     (↗︎)
                 Medium                  (↗︎)
                 Very High               (↗︎)
                 Very Low                (↗︎)
ROC AUC          High                    (↗︎)
                 Low                     (↗︎)
                 Medium                  (↗︎)
                 Very High               (↗︎)
                 Very Low                (↗︎)
Log loss                                 (↘︎)
Fit time (s)                             (↘︎)
Predict time (s)                         (↘︎)

In [81]:
report.metrics.accuracy()

Output()

         HistGradientBoostingClassifier
                                   mean       std
Metric
Accuracy                       0.398069  0.008458

In [74]:
display = report.metrics.roc()
display

skore.RocCurveDisplay(...)

In [66]:
display.roc_curve["label"].cat.categories

Index(['High', 'Low', 'Medium', 'Very High', 'Very Low'], dtype='object')